name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use Bun, not Node
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      # Install using Bun's lockfile
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Enforce code quality
      - name: Type Check
        run: bun run check-types

      - name: Lint
        run: bun run lint

      # This runs esbuild --production, which includes size limit check
      - name: Build & Check Size
        run: bun run packprod

      # Run Unit Tests
      - name: Run Tests
        run: bun run test
